name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Test version
      run: test "$(echo $(cat version.txt))" == ${{ github.event.release.tag_name }}
      shell: bash

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build and Publish with Gradle
      run: ./gradlew --no-daemon build

    - name: Upload tarball to release
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: build/distributions/catalog-export-${{ github.event.release.tag_name }}.tar.gz
        asset_name: catalog-export-${{ github.event.release.tag_name }}.tar.gz
        asset_content_type: application/gzip

    - name: Upload zip to release
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: build/distributions/catalog-export-${{ github.event.release.tag_name }}.zip
        asset_name: catalog-export-${{ github.event.release.tag_name }}.zip
        asset_content_type: application/zip

